// <auto-generated />
namespace DoctorIdWeb.Infraestrutura.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Criacao_Tabela_Pacientes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criacao_Tabela_Pacientes));
        
        string IMigrationMetadata.Id
        {
            get { return "202004132237177_Criacao_Tabela_Pacientes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
